apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          image: 100xdevs/chat-app-websocket:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: REDIS_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: websocket
  namespace: chat-app
spec:
  type: ClusterIP
  selector:
    app: websocket
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
